language: python
install:
  - pip install -r requirements.txt
script: bash ./deploy.sh
notifications:
  email: false
env:
  global:
  - ENCRYPTION_LABEL: "b40e9c1f35ae"
  - COMMIT_AUTHOR_EMAIL: "you@example.com"
